In [1]:
import pandas as pd
import numpy as np
import sys
import math
from pickled import *

In [2]:
clf_elec_interest = unpickled("clf_elec_interest")
clf_indus_interest = unpickled("clf_indus_interest")
clf_meca_interest = unpickled("clf_meca_interest")

In [3]:
data = pd.read_csv('temp csv/X_interest.csv')
data.head()
data.drop(["FILIERE","Unnamed: 0"],inplace=True,axis=1)

In [4]:
#Indus
liste = data.iloc[300,:].values.reshape(1,-1)
X_indus = clf_indus_interest.predict(liste)
print(X_indus)
for j in range(len(X_indus[0])) : 
    X_indus[0][j] = round(X_indus[0][j]*5) 
    if X_indus[0][j] == 0 :
        X_indus[0][j] += 1
print(X_indus[0])

[[0.2275 0.075  0.4075 0.715  0.37  ]]
[1. 1. 2. 4. 2.]


In [5]:
#meca
liste = data.iloc[300,:].values.reshape(1,-1)
X_meca = clf_meca_interest.predict(liste)
print(X_meca)
for j in range(len(X_meca[0])) : 
    X_meca[0][j] = round(X_meca[0][j]*5) 
    if X_meca[0][j] == 0 :
        X_meca[0][j] += 1
print(X_meca[0])

[[0.25  0.    0.525 0.75  0.25 ]]
[1. 1. 3. 4. 1.]


In [6]:
#elec
liste = data.iloc[301,:].values.reshape(1,-1)
X_elec = clf_elec_interest.predict(liste)
print(X_elec)
for j in range(len(X_elec[0])) : 
    X_elec[0][j] = round(X_elec[0][j]*5) 
    if X_elec[0][j] == 0 :
        X_elec[0][j] += 1
print(X_elec[0])

[[0.145  0.205  0.1525 0.2475 0.2175]]
[1. 1. 1. 1. 1.]


In [7]:
print("Industriel : {}".format(X_indus[0]))
print("Mécanique : {}".format(X_meca[0]))
print("Electrique : {}".format(X_elec[0]))
print("Industriel : " + "".join([str(x*20)+"% " for x in X_indus[0]]))
print("Mécanique : " + "".join([str(x*20)+"% " for x in X_meca[0]]))
print("Electrique : " + "".join([str(x*20)+"% " for x in X_elec[0]]))

Industriel : [1. 1. 2. 4. 2.]
Mécanique : [1. 1. 3. 4. 1.]
Electrique : [1. 1. 1. 1. 1.]
Industriel : 20.0% 20.0% 40.0% 80.0% 40.0% 
Mécanique : 20.0% 20.0% 60.0% 80.0% 20.0% 
Electrique : 20.0% 20.0% 20.0% 20.0% 20.0% 
